export const ADD_ING = 'ADD_INGREDIENTS'
export const REM_ING = 'REMOVE_INGREDIENTS'
export const SET_INIT_ING = 'SET_INITIAL_INGREDIENTS'
export const ING_FETCH_FAIL = 'INGREDIENTS_FETCH_FAILED'

export const ORD_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const ORD_FAILURE = 'PLACE_ORDER_FAILED'
export const ORD_PLACE_START = 'PLACE_ORDER_START'
export const ORD_INIT = 'ORDER_INITIALIZATION'

export const FETCH_ORD_START = 'FETCH_ORDER_START'
export const FETCH_ORD_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORD_FAIL = 'FETCH_ORDER_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT'